# Site settings
title: Ranelagh Ultimate
header-img: img/main.jpg
email: your-email@yourdomain.com
description: "Team website for Dublin based team; Ranelagh Ultimate"
baseurl: "/ranelaghfc"
url: "http://yourdomain.com"
twitter_username: RanelaghULT
facebook_username:  RanelaghUltimate
author: Ross Andreucetti
author_webite: http://randreucetti.com
roster_years: [2015, 2014, 2013, 2012]

# Build settings
markdown: kramdown
gems: [jekyll-paginate]
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
