# Site settings
title: Ranelagh Ultimate
header-img: img/main.jpg
email: your-email@yourdomain.com
description: "Team website for Dublin based team; Ranelagh Ultimate"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: RanelaghULT
facebook_username:  RanelaghUltimate
author: Ross Andreucetti
author_webite: http://randreucetti.com
comments: true

# Build settings
markdown: kramdown
gems: [jekyll-paginate]
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
